"  General Settings  
set number

" Enable syntax hightlighting
syntax on

" Automatically indent with open bracket
set smartindent

" Tabs are set to 4 spaces.
" This is also in the Python PEP
set shiftwidth=4
set tabstop=4
set expandtab
set smarttab

" Show line number, cursor position.
set ruler

" Vim-Plug Plugins
call plug#begin()
Plug 'scrooloose/nerdtree'
Plug 'vimwiki/vimwiki'
call plug#end()

" VIM Mappings
map <C-n> :NERDTreeToggle<CR>

" Vim-Wiki Mappings
set nocompatible
filetype plugin on
"let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]
let wiki_1 = {}
let wiki_1.path = '~/vimwiki_work_md/'
let wiki_1.syntax = 'markdown'
let wiki_1.ext = '.md'

let wiki_2 = {}
let wiki_2.path = '~/vimwiki_personal_md/'
let wiki_2.syntax = 'markdown'
let wiki_2.ext = '.md'

let g:vimwiki_list = [wiki_1, wiki_2]
let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
